apiVersion: v2
name: logger
home: https://github.com/teamhephy/logger
version: 2.5.3
description: In-memory log buffer used by Hephy Workflow.
maintainers:
- name: Team Hephy
  email: team@teamhephy.com
